import type { Metadata } from "next";
import localFont from "next/font/local";
import "@notpadd/ui/styles/globals.css";
import "@notpadd/ui/styles/prose-mirror.css";
import Providers from "@/components/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

// <motion.div
//   className="absolute left-[-50%] top-[-50%] h-[200%] w-[200%] bg-[conic-gradient(from_0deg,transparent_0%,#4DAFFE_10%,#4DAFFE_25%,transparent_35%)]"
//   animate={{ rotate: 360 }}
//   transition={{
//     duration: 1.25,
//     repeat: Infinity,
//     ease: "linear",
//     repeatType: "loop",
//   }}
// />;
